USE TENNIS;
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.STATUS_LOOKUP'))
BEGIN
	Print('Creating Status lookup table...')
	
	CREATE TABLE [STATUS_LOOKUP](
		[ID] [int] NOT NULL,
		[NAME] [nvarchar](50) NOT NULL
		CONSTRAINT [PK_STATUS_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]	

	INSERT INTO STATUS_LOOKUP VALUES (1, 'Not Started');
	INSERT INTO STATUS_LOOKUP VALUES (2, 'In Progress');
	INSERT INTO STATUS_LOOKUP VALUES (3, 'Completed');
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.POINT_LOOKUP'))
BEGIN
	Print('Creating Point lookup table...')
	
	CREATE TABLE [POINT_LOOKUP](
		[ID] [int] NOT NULL,
		[NAME] [nvarchar](50) NOT NULL
		CONSTRAINT [PK_POINT_ID] PRIMARY KEY CLUSTERED(
			[Id] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]	

	INSERT INTO POINT_LOOKUP VALUES (0, 'Love');
	INSERT INTO POINT_LOOKUP VALUES (1, 'Fifteen');
	INSERT INTO POINT_LOOKUP VALUES (2, 'Thirty');
	INSERT INTO POINT_LOOKUP VALUES (3, 'Forty');
	INSERT INTO POINT_LOOKUP VALUES (4, 'Advantage');
	INSERT INTO POINT_LOOKUP VALUES (5, 'Deuce');
	INSERT INTO POINT_LOOKUP VALUES (6, 'GamePoint');		
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MATCH'))
BEGIN
	Print('Creating Match table...')
	
	CREATE TABLE [MATCH](
		[ID] [uniqueidentifier] NOT NULL,
		[NAME] [nvarchar](100) NOT NULL,
		[STARTED_ON] [datetime] NOT NULL,
		[COMPLETED_ON] [datetime] NULL,
		[STATUS_ID] [int] NOT NULL
		CONSTRAINT [PK_MATCH_ID] PRIMARY KEY CLUSTERED(
			[Id] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [MATCH] WITH CHECK ADD 
		CONSTRAINT [FK_MATCH_FROM_STATUS_LOOKUP] FOREIGN KEY([STATUS_ID]) REFERENCES [STATUS_LOOKUP] ([ID])
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.PLAYER'))
BEGIN
	Print('Creating Player table...')
	
	CREATE TABLE [PLAYER](
		[ID] [uniqueidentifier] NOT NULL,
		[FIRST_NAME] [nvarchar](50) NOT NULL,
		[SUR_NAME] [nvarchar](50) NOT NULL,
		[LAST_NAME] [nvarchar](50) NULL,
		[DATE_OF_BIRTH] [datetime] NOT NULL,
		[CLUB] [nvarchar](100) NULL,				
		CONSTRAINT [PK_PLAYER_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]

	INSERT INTO PLAYER(ID, FIRST_NAME, SUR_NAME, DATE_OF_BIRTH)
		VALUES(NEWID(), 'Bernhard', 'Ritter', '10-Jul-1978');
	INSERT INTO PLAYER(ID, FIRST_NAME, SUR_NAME, DATE_OF_BIRTH)
		VALUES(NEWID(), 'Steffen', 'Wuest', '5-Jan-1971');
	INSERT INTO PLAYER(ID, FIRST_NAME, SUR_NAME, DATE_OF_BIRTH)
		VALUES(NEWID(), 'Andreas', 'Risch', '18-Oct-1968');	
	INSERT INTO PLAYER(ID, FIRST_NAME, SUR_NAME, DATE_OF_BIRTH)
		VALUES(NEWID(), 'Syed', 'Ghouse', '07-Aug-1973');	
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.MATCH_PLAYER'))
BEGIN
	Print('Creating Match Player table...')
	
	CREATE TABLE [MATCH_PLAYER](
		[ID] [uniqueidentifier] NOT NULL,
		[MATCH_ID] [uniqueidentifier] NOT NULL,
		[PLAYER_ID] [uniqueidentifier] NOT NULL			
		CONSTRAINT [PK_MATCH_PLAYER_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [MATCH_PLAYER] WITH CHECK ADD 
		CONSTRAINT [FK_MATCH_PLAYER_FROM_MATCH] FOREIGN KEY([MATCH_ID]) REFERENCES [MATCH] ([ID]),
		CONSTRAINT [FK_MATCH_PLAYER_FROM_PLAYER] FOREIGN KEY([PLAYER_ID]) REFERENCES [PLAYER] ([ID])
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.SET_SCORE'))
BEGIN
	Print('Creating Set Score table...')
	
	CREATE TABLE [SET_SCORE](
		[ID] [uniqueidentifier] NOT NULL,
		[MATCH_ID] [uniqueidentifier] NOT NULL,
		[WON_BY] [uniqueidentifier] NULL,
		[STARTED_ON] [datetime] NOT NULL,
		[COMPLETED_ON] [datetime] NULL,
		[STATUS_ID] [int] NOT NULL		
		CONSTRAINT [PK_SET_SCORE_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [SET_SCORE] WITH CHECK ADD 
		CONSTRAINT [FK_SET_SCORE_FROM_MATCH] FOREIGN KEY([MATCH_ID]) REFERENCES [MATCH] ([ID]),			
		CONSTRAINT [FK_SET_SCORE_FROM_PLAYER] FOREIGN KEY([WON_BY]) REFERENCES [PLAYER] ([ID]),
		CONSTRAINT [FK_SET_SCORE_FROM_STATUS_LOOKUP] FOREIGN KEY([STATUS_ID]) REFERENCES [STATUS_LOOKUP] ([ID])
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.GAME_SCORE'))
BEGIN
	Print('Creating Game Score table...')
	
	CREATE TABLE [GAME_SCORE](
		[ID] [uniqueidentifier] NOT NULL,
		[SET_ID] [uniqueidentifier] NOT NULL,
		[SERVED_BY] [uniqueidentifier] NOT NULL,
		[WON_BY] [uniqueidentifier] NULL,
		[STARTED_ON] [datetime] NOT NULL,
		[COMPLETED_ON] [datetime] NULL,
		[STATUS_ID] [int] NOT NULL			
		CONSTRAINT [PK_GAME_SCORE_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [GAME_SCORE] WITH CHECK ADD 
		CONSTRAINT [FK_GAME_SCORE_FROM_SET_SCORE] FOREIGN KEY([SET_ID]) REFERENCES [SET_SCORE] ([ID]),			
		CONSTRAINT [FK_GAME_SCORE_FROM_PLAYER_1] FOREIGN KEY([SERVED_BY]) REFERENCES [PLAYER] ([ID]),
		CONSTRAINT [FK_GAME_SCORE_FROM_PLAYER_2] FOREIGN KEY([WON_BY]) REFERENCES [PLAYER] ([ID]),
		CONSTRAINT [FK_GAME_SCORE_FROM_STATUS_LOOKUP] FOREIGN KEY([STATUS_ID]) REFERENCES [STATUS_LOOKUP] ([ID])
END
GO

IF NOT EXISTS(SELECT * FROM sys.columns WHERE object_id = OBJECT_ID('dbo.POINT_SCORE'))
BEGIN
	Print('Creating Point Score table...')
	
	CREATE TABLE [POINT_SCORE](
		[ID] [uniqueidentifier] NOT NULL,
		[GAME_ID] [uniqueidentifier] NOT NULL,
		[PLAYER_ID] [uniqueidentifier] NOT NULL,
		[POINT_ID] [int] NOT NULL,
		[UPDATED_ON] [datetime] NOT NULL		
		CONSTRAINT [PK_POINT_SCORE_ID] PRIMARY KEY CLUSTERED(
			[ID] ASC
		)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	ALTER TABLE [POINT_SCORE] WITH CHECK ADD 
		CONSTRAINT [FK_POINT_SCORE_FROM_GAME_SCORE] FOREIGN KEY([GAME_ID]) REFERENCES [GAME_SCORE] ([ID]),			
		CONSTRAINT [FK_POINT_SCORE_FROM_PLAYER] FOREIGN KEY([PLAYER_ID]) REFERENCES [PLAYER] ([ID]),		
		CONSTRAINT [FK_POINT_SCORE_FROM_POINT_LOOKUP] FOREIGN KEY([POINT_ID]) REFERENCES [POINT_LOOKUP] ([ID])
END
GO